name: mixin_bot_sdk_dart
description: Mixin API for Dart/Flutter
version: 0.0.1
homepage: https://github.com/MixinNetwork/mixin_bot_sdk_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cryptography: ^1.4.1
  convert: ^2.1.1
  jose:
    git:
        url: git@github.com:Tougee/jose.git
        ref: feature/eddsa

  sprintf: ^5.0.0
  uuid: ^2.2.2
  dio: ^3.0.10
  json_annotation: ^3.1.1
  crypto: ^2.1.5
  meta: ^1.2.4
  equatable: ^1.2.5


dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.2
  build_runner: ^1.10.11
  json_serializable: ^3.5.1

