name: mixin_bot_sdk_dart
description: Mixin Messenger API for Dart/Flutter, build decentrialized applications on Mixin
version: 0.1.0
homepage: https://github.com/MixinNetwork/mixin_bot_sdk_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  dart_jsonwebtoken: ^2.3.2
  sprintf: ^6.0.0
  uuid: ^3.0.4
  dio: ^4.0.0
  json_annotation: ^4.0.1
  crypto: ^3.0.1
  meta: ^1.4.0
  equatable: ^2.0.3
  enum_to_string: ^2.0.1
  recase: ^4.0.0
  ed25519_edwards: ^0.2.1
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.9
  very_good_analysis: ^2.1.2
#  pedantic: ^1.11.0
  build_runner:
  json_serializable: ^5.0.0
