name: mixin_bot_sdk_dart
description: Mixin API for Dart/Flutter
version: 0.0.1
homepage: https://github.com/MixinNetwork/mixin_bot_sdk_dart
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  convert: ^3.0.0
  dart_jsonwebtoken: ^2.1.0
  sprintf: ^6.0.0
  uuid: ^3.0.4
  dio: ^4.0.0
  json_annotation: ^4.0.1
  crypto: ^3.0.1
  meta: ^1.3.0
  equatable: ^2.0.0
  enum_to_string: ^2.0.1
  recase: ^4.0.0
  ed25519_edwards: ^0.1.0

dev_dependencies:
  test: ^1.17.1
  very_good_analysis: ^2.1.1
#  pedantic: ^1.11.0
  build_runner:
  json_serializable: ^4.1.1
