name: bot_api_dart_client
description: Mixin API for Dart/Flutter
version: 0.0.1
homepage: https://github.com/MixinNetwork/bot_api_dart_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cryptography: ^1.4.1
  convert: ^2.1.1
  jose:
    git:
        url: git@github.com:Tougee/jose.git
        ref: feature/eddsa

  sprintf: "^4.0.0"
  uuid: ^2.2.0
  dio: ^3.0.10
  json_annotation: ^3.0.0
  crypto: ^2.1.5

dev_dependencies:
  test: ^1.15.1
  pedantic: ^1.9.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

