name: mixin_bot_sdk_dart
description: Mixin API for Dart/Flutter
version: 0.0.1
homepage: https://github.com/MixinNetwork/mixin_bot_sdk_dart
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  convert: ^3.0.0

  dart_jsonwebtoken:
    git:
      url: git@github.com:MixinNetwork/jsonwebtoken.git
      ref: nullsafety

  sprintf: ^6.0.0-nullsafety
  uuid: ^3.0.1
  dio: ^4.0.0-beta7
  json_annotation: ^4.0.0
  crypto: ^3.0.0
  meta: ^1.3.0
  equatable: ^2.0.0-nullsafety.4
  enum_to_string: ^2.0.0-nullsafety.1
  recase: ^4.0.0-nullsafety.0
  ed25519_edwards: ^0.1.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
  build_runner: ^1.12.1
  json_serializable: ^4.0.3
